project:
  type: website
  output-dir: docs
website:
  title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - Travels.qmd
      - Cats.qmd

format:
  html:
    theme: Cyborg
    css: styles.css
    toc: true

editor: visual

